### ISSUE TITLE
Can't get errorhandler to work in Express 4

### ISSUE THREAD

**Issue by rahmatawaludin** [expressjs/errorhandler#16]
I'm new in this. I have this code:

```
    var express = require('express')
    var responseTime = require('response-time')
    var errorhandler = require('errorhandler')
    var app = express()
    
    // view engine
    app.set('view engine', 'jade')
    
    // middleware
    app.use(express.static('public'))
    app.use(responseTime())
    app.use(errorhandler({log: false}))
    
    app.get('/', function (req, res) {
      // res.render('index')
      fails()
    })
    
    app.listen(3000)

```
When I hit `/` I thought I should get the errorhandler in styled html, but it just shown like this:

![screen shot 2016-02-04 at 9 06 23 am](https://cloud.githubusercontent.com/assets/1274849/12803872/8862f196-cb20-11e5-808e-ea56649b08ad.png)

What should I do to show the errorhandler html on the response??

**Comment by jordonias** [comment]
Your error handler should be after the routes. Also `fails()` is not defined, I think you're looking to use `next()` but it should be one of the arguments like `function(req, res, next)`.

```js
var express = require('express');
var errorHandler = require('errorhandler');

var app = express();

app.get('/', function(req, res, next) {
  return next(new Error('some error'));
});

app.use(errorHandler());

app.listen(3000);
```

It will also work if an error is thrown like:

```js
var express = require('express');
var errorHandler = require('errorhandler');

var app = express();

app.get('/', function(req, res, next) {
  throw new Error('some error');
});

app.use(errorHandler());

app.listen(3000);
```

You'll want to review some of the api documentation, specifically:
http://expressjs.com/en/guide/using-middleware.html
http://expressjs.com/en/guide/error-handling.html

**Comment by kelthenoble** [comment]
Yeah  @rahmatawaludin, like @jordonias said, you always wanna `define errors` after you're `routes`. 
And @jordonias i think that would be really cool, as discussed on `gitter` to do a pull request with more `error handling` examples. :+1:

**Comment by jordonias** [comment]
At a bare minimum there should be a link in **README.md** to the error-handling guide in the `expressjs.com` docs.

**Comment by kelthenoble** [comment]
True :100:

**Comment by jordonias** [comment]
You can start one if you'd like. I won't have time until later.

**Comment by kelthenoble** [comment]
Yea, me as well, i'll have it done tonight.

**Comment by dougwilson** [comment]
I'm going to close this issue since the question was ultimately answered :)
