### ISSUE TITLE
Allow to change output structor

### ISSUE THREAD

**Issue by wxs77577** [expressjs/errorhandler#23]
I don't need `{error: {...}}`, could we change the output structor?

**Comment by dougwilson** [comment]
Why does the structure matter for development? Don't you want to know what the error is when developing?

**Comment by wxs77577** [comment]
I wanna use it in production mode, if any where throw an error, it sends an json like `{statusCode: 422, message: 'Username is required.'}`.

**Comment by dougwilson** [comment]
This module has no product mode. The description of this module is the following:

> Development-only error handler middleware.

> This middleware is only intended to be used in a development environment, as the full error stack traces and internal details of any object passed to this module will be sent back to the client when an error occurs.
