### ISSUE TITLE
No matching version found for errorhandler@^1.5.1

### ISSUE THREAD

**Issue by levitomer** [expressjs/errorhandler#24]
Hi,

I was trying to `npm i -D json-server`. unfortunately, I got the following error:
![image](https://user-images.githubusercontent.com/18260079/69915942-707d5f00-145d-11ea-9d10-a9f58acbb10f.png)

I checked errorhandler at npm, and indeed the version is clearly 1.5.1:
![image](https://user-images.githubusercontent.com/18260079/69915955-999def80-145d-11ea-8fef-dc25166db8ce.png)

However, `npm view errorhandler` shows a different version:
![image](https://user-images.githubusercontent.com/18260079/69915958-a4f11b00-145d-11ea-9697-571a2e44f323.png)

FYI

Related issue:  [No matching version found for errorhandler@^1.5.1](https://github.com/typicode/json-server/issues/1054)

**Comment by dougwilson** [comment]
The public npm registry seems to show it correctly. Based on the tarball address in your screenshot, I believe you are using a mirror, which seems to have the wrong data resulting in your error. Please try the official npm registry and if that still doesn't work screenshot the npm view you see on the public registry and I can reopen to investigate further.

**Comment by levitomer** [comment]
Hi @dougwilson,

I am trying to understand your instructions, can you be more specific?

Note: I am not using errorhandler.. I used `npm view` in order to understand why I got this error when I installed [json-server](https://www.npmjs.com/package/json-server).

**Comment by dougwilson** [comment]
I didn't provide any instructions, so not sure what you mean. I think it's more like as far as I can tell the version is up there. I tried to npm publish which errored that the versions was already there. If you can provide some specific instructions on how I can fix this if you believe it is something I can fix, let me know what they are and I can reopen the issue.

**Comment by dougwilson** [comment]
<img width="676" alt="Screen Shot 2019-12-09 at 10 37 36 AM" src="https://user-images.githubusercontent.com/67512/70449414-f0b04f80-1a6f-11ea-92c5-5febeb529277.png">
